# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10
  
#[[main]]
#  name = "Academic positions"
 # url = "#experience"
 # weight = 20

#[[main]]
  #name = "Posts"
 # url = "#posts"
 # weight = 20
#[[main]]
#  name = "My new page"  # A link title for your page.
#  url = "example/"  # The URL of your page.
#  weight = 15  # The position of your page in the menu.
  
[[main]]
  name = "Published Work"
  url = "#publication2"
  weight = 25
  
 [[main]]
  name = "Ongoing Work"
  url = "#publications3"
  weight = 30 

[[main]]
  name = "Data"
  url = "#projects"
  weight = 40
  
    [[main]]
  name = "Teaching"
  url = "#teaching"
  weight = 45
  
 [[main]]
  name = "Events"
  url = "#talks"
  weight = 50

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60
  
 [[main]]
  name = "Blog"  # Title of the link.
  url = "blog/"  # Widget Page folder name.
  weight = 70  # Position of the link in the navigation bar.
  
#  [[main]]
#  name = "hello"  # Title of the link.
#  url = "blog2/"  # Widget Page folder name.
#  weight = 80  # Position of the link in the navigation bar.

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
 #[[main]]
   # name = "CV - السيرة الذاتية"
   # url = "files/cv.pdf"
   # weight = 80
