# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home - عني "
  url = "#about"
  weight = 10
  
#[[main]]
#  name = "Academic positions - وظائف أكاديمية"
 # url = "#experience"
 # weight = 20

#[[main]]
  #name = "Posts"
 # url = "#posts"
 # weight = 20
#[[main]]
#  name = "My new page"  # A link title for your page.
#  url = "example/"  # The URL of your page.
#  weight = 15  # The position of your page in the menu.
  
[[main]]
  name = "Research - أبحاثي"
  url = "#hero"
  weight = 25

[[main]]
  name = "Data - قواعد بيانات "
  url = "#projects"
  weight = 40
  
 [[main]]
  name = "Events - فعاليات "
  url = "#talks"
  weight = 45

[[main]]
  name = "Contact - للتواصل معي "
  url = "#contact"
  weight = 50
  
 [[main]]
  name = "Blog - مدونتي "  # Title of the link.
  url = "landing/"  # Widget Page folder name.
  weight = 70  # Position of the link in the navigation bar.

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
 [[main]]
    name = "CV - السيرة الذاتية"
    url = "files/cv.pdf"
    weight = 80
